### ISSUE TITLE
Compliance with CMAC 

### ISSUE THREAD

**Issue by raed667** [allan-stewart/node-aes-cmac#1]
Hello, 

First, thank you for the lib.
I have been experimenting with it for the last hour or so.

I'm getting hashes from a JAVA code that uses [CMAC.Bouncycastle](http://www.cs.berkeley.edu/~jonah/bc/org/bouncycastle/crypto/macs/CMac.html). 

``` java
        final CipherParameters params = new KeyParameter(key);
        BlockCipher blockCipher = new AESFastEngine();
        CMac mac = new CMac(blockCipher);
        mac.init(params);
        mac.update(macInput, 0, 16);
        mac.doFinal(outMac, 0);
```

Where `key`and `macInput`= 00000000000000000000000000000000000000
I get `585B59132919F43A3AF75AB1A7E80CAC`

---

Now using the 'node-aes-cmac' lib 

``` javascript
var aesCmac = require('./lib/aes-cmac');

var keyMac = new Buffer(key, 'hex');
var msg = new Buffer(macInput);
var result = aesCmac.aesCmac(keyMac, msg);
```

result = `4f2c3a695beb46e57ba75c0e246eb400`

Am I doing something wrong or are you not using the same OMAC1 standard ?

**Comment by arjenvanderende** [comment]
How did you derive the byte arrays for `key` and `macInput` in the Java example?
In your example I think the length you specify in `update` is too short (should be 32 instead of 16).

``` java
    byte[] key = DatatypeConverter.parseHexBinary("00000000000000000000000000000000");
    byte[] macInput = "00000000000000000000000000000000".getBytes();
    byte[] outMac = new byte[16];

    BlockCipher blockCipher = new AESFastEngine();
    CMac mac = new CMac(blockCipher);
    mac.init(new KeyParameter(key));
    mac.update(macInput, 0, macInput.length);
    mac.doFinal(outMac, 0);

    String signature = DatatypeConverter.printHexBinary(outMac);
```

Using the code sample above, signature = `4F2C3A695BEB46E57BA75C0E246EB400` which matches the result you generated with NodeJS.

**Comment by raed667** [comment]
@arjenvanderende you're right dear sir, my bad!
